### ISSUE TITLE
[Spaces] Document Spaces for 3.0+

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs-client-desktop#320]
ownCloud 3.0+ Desktop app supports oCIS Spaces:

- [ ] Pre-3.0 accounts can't be migrated to 3.0+ Spaces accounts. Needs new account setup
- [ ] oC10 accounts can't be migrated to oCIS Spaces accounts. Needs new account setup
- [ ] Default: All existing/active Spaces get added at initial account setup
- [ ] Default: Personal, Shares and Spaces are placed in a parent folder, that gets linked from file manager sidebars (https://github.com/owncloud/client/issues/9821, https://github.com/owncloud/client/issues/9838)
- [ ] New Spaces don't get added automatically (planned feature)
- [ ] 3.0+ with Spaces doesn't have the option to sync subfolders (planned feature)
- [ ] Spaced deleted or disabled on the server doesn't get deleted (https://github.com/owncloud/client/issues/10285, https://github.com/owncloud/client/issues/10257 , https://github.com/owncloud/client/issues/9700)
- [ ] Spaces renamed on the server doesn't change locally. Only content inside changes (https://github.com/owncloud/client/issues/10284)

**Comment by michaelstingl** [comment]
Additional for 4.0+:

- [ ] https://github.com/owncloud/client/pull/10602
